"""Build index.html for EduML: take the vendored CSS from the EnvML page and
inline model/model.json into the single-file demo."""
import json, os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Vendored Tailwind snapshot (extracted once from the EnvML page) so this
# repository has zero external dependencies at build time.
with open(os.path.join(HERE, 'src', 'vendored.css.html'), encoding='utf-8') as f:
    CSS = f.read()

with open(f'{HERE}/model/model.json', encoding='utf-8') as f:
    model = json.load(f)

MODEL_JS = json.dumps(model, separators=(',', ':'))

HTML = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>EduML · Learning Analytics At-Risk Prediction Demo</title>
<meta name="description" content="Enter student engagement and attendance indicators and predict a performance level and a three-band performance class with gradient-boosted trees. Full cross-validated evaluation shown alongside trivial baselines.">

<!--
  EduML — Learning Analytics Prediction Demo
  MIT licensed — see LICENSE in the repository.

  This file is generated by scripts/build_page.py from model/model.json.
  To retrain: python3 scripts/train_model.py
  To rebuild: python3 scripts/build_page.py

  The page has NO network dependencies: no CDN, no fonts, no API, no backend.
  It is one file and it works by double-clicking it, offline, from disk.
-->
__CSS__
<!-- ------------------------------------------------------------------
     EduML theme overrides (hand-written), applied after the vendored
     Tailwind snapshot. Violet identity, deliberately distinct from the
     blue used by the sibling EnvML demo.
     ------------------------------------------------------------------ -->
<style>
  body { background-color:#f5f3ff !important; }          /* violet-50  */
  .bg-ink-900 { background-color:#2e1065 !important; }   /* deep violet header */
  .text-ink-800 { color:#312e81 !important; }            /* indigo-900 body ink */
  .text-blue-700 { color:#6d28d9 !important; }           /* violet-700 */
  .bg-blue-500 { background-color:#8b5cf6 !important; }  /* violet-500 */
  .bg-blue-600 { background-color:#7c3aed !important; }  /* violet-600 */
  .border-blue-600 { border-color:#8b5cf6 !important; }
  .text-blue-600 { color:#7c3aed !important; }
  input[type="range"] { accent-color:#7c3aed; }
  * { --tw-ring-color:rgb(124 58 237 / 0.45); }
  ::selection { background:#ddd6fe; color:#2e1065; }
</style>
</head>
<body class="bg-slate-100 text-ink-800">

<!-- ==================================================================
     Page header
     ================================================================== -->
<header class="bg-ink-900 text-white">
  <div class="max-w-6xl mx-auto px-5 py-7">
    <h1 class="text-2xl sm:text-3xl font-semibold tracking-tight">EduML — Learning Analytics Demo</h1>
    <p class="mt-2 text-slate-300 text-sm sm:text-base leading-relaxed max-w-3xl">
      Enter a student&rsquo;s engagement indicators, absence band and semester to obtain a
      predicted performance level and a three-band performance class
      (Low / Medium / High), using gradient-boosted trees.
    </p>
    <p class="mt-3 text-slate-400 text-xs leading-relaxed max-w-3xl">
      <strong class="text-slate-300">Sample size.</strong>
      The source dataset contains <span id="hdr-raw"></span> student records
      from the Kalboard&nbsp;360 learning management system. <span id="hdr-rows"></span> records
      were used for modelling. All performance figures on this
      page are <strong class="text-slate-300">out-of-fold</strong> cross-validated:
      the data were divided into <span id="hdr-folds"></span> folds, and each figure was
      calculated on the <span id="hdr-testsize"></span> records held out by a fold, using a
      model fitted on the remaining <span id="hdr-trainsize"></span> records. No record is
      therefore used to score a model that was fitted on it. Each reported figure is shown
      beside the simplest possible baseline for comparison.
    </p>
  </div>
</header>

<main class="max-w-6xl mx-auto px-5 py-7 space-y-6">

  <!-- ==================================================================
       Section 1 + 2: inputs on the left, prediction on the right.
       ================================================================== -->
  <section class="grid grid-cols-1 lg:grid-cols-2 gap-6">

    <!-- ---------- 1. Input panel ---------- -->
    <div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
      <div class="flex items-center justify-between mb-4 gap-3">
        <h2 class="font-semibold text-lg">1 · Student indicators</h2>
        <button id="btn-random" class="text-xs px-3 py-1.5 rounded-md bg-slate-100 hover:bg-slate-200 border border-slate-300 whitespace-nowrap">
          Load a random real student
        </button>
      </div>

      <div class="space-y-4">
        <div>
          <label class="flex justify-between text-sm font-medium mb-1">
            <span>Raised hands · raisedhands</span><span class="num text-blue-700" id="v-raisedhands"></span>
          </label>
          <input type="range" id="in-raisedhands" class="w-full">
          <p class="text-[11px] text-slate-500 mt-1">Number of times the student raised a hand in class &middot; <span id="r-raisedhands"></span></p>
        </div>

        <div>
          <label class="flex justify-between text-sm font-medium mb-1">
            <span>Visited resources · VisITedResources</span><span class="num text-blue-700" id="v-VisITedResources"></span>
          </label>
          <input type="range" id="in-VisITedResources" class="w-full">
          <p class="text-[11px] text-slate-500 mt-1">Number of course resources opened in the LMS &middot; <span id="r-VisITedResources"></span></p>
        </div>

        <div>
          <label class="flex justify-between text-sm font-medium mb-1">
            <span>Announcements viewed · AnnouncementsView</span><span class="num text-blue-700" id="v-AnnouncementsView"></span>
          </label>
          <input type="range" id="in-AnnouncementsView" class="w-full">
          <p class="text-[11px] text-slate-500 mt-1">Number of course announcements viewed &middot; <span id="r-AnnouncementsView"></span></p>
        </div>

        <div>
          <label class="flex justify-between text-sm font-medium mb-1">
            <span>Discussion messages · Discussion</span><span class="num text-blue-700" id="v-Discussion"></span>
          </label>
          <input type="range" id="in-Discussion" class="w-full">
          <p class="text-[11px] text-slate-500 mt-1">Messages posted in course discussions &middot; <span id="r-Discussion"></span></p>
        </div>

        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-medium mb-1">Absence days</label>
            <div class="grid grid-cols-2 gap-2" id="in-absence">
              <button data-v="0" class="py-2 rounded-md text-sm border">Under 7</button>
              <button data-v="1" class="py-2 rounded-md text-sm border">7 or more</button>
            </div>
          </div>
          <div>
            <label class="block text-sm font-medium mb-1">Semester</label>
            <div class="grid grid-cols-2 gap-2" id="in-semester">
              <button data-v="0" class="py-2 rounded-md text-sm border">First</button>
              <button data-v="1" class="py-2 rounded-md text-sm border">Second</button>
            </div>
          </div>
        </div>
        <!-- Note: absence band and semester are the only non-engagement inputs. -->
      </div>
    </div>

    <!-- ---------- 2. Prediction panel ---------- -->
    <div class="space-y-4">
      <div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
        <h2 class="font-semibold text-lg mb-4">2 · Model prediction</h2>

        <div class="grid grid-cols-2 gap-4 items-end">
          <div>
            <p class="text-xs text-slate-500">Predicted performance level</p>
            <p class="num text-4xl font-semibold leading-tight" id="out-perf">&mdash;</p>
            <p class="text-xs text-slate-500">on a 0&ndash;2 scale (0 = Low, 2 = High) &middot; 80% of outcomes fall in <span id="out-lo" class="num"></span> &ndash; <span id="out-hi" class="num"></span></p>
          </div>
          <div class="text-right">
            <p class="text-xs text-slate-500">Performance class</p>
            <p id="out-class" class="text-2xl font-semibold">&mdash;</p>
            <p id="out-band" class="text-xs text-slate-500"></p>
          </div>
        </div>

        <!-- Performance scale: three bands, Low / Medium / High. -->
        <div class="mt-5">
          <div class="relative h-7 rounded overflow-hidden flex">
            <div class="flex-1" style="background:#ef4444"></div>
            <div class="flex-1" style="background:#eab308"></div>
            <div class="flex-1" style="background:#22c55e"></div>
          </div>
          <div class="relative h-4 text-[10px] text-slate-500 num">
            <span class="absolute left-0">Low</span>
            <span class="absolute left-[47%]">Medium</span>
            <span class="absolute right-0">High</span>
          </div>
          <div class="relative h-0">
            <div class="absolute -top-9 w-0.5 h-7 bg-ink-900 transition-all" id="marker-bar" style="left:0"></div>
          </div>
          <p class="text-[11px] text-slate-500">Bands split the 0&ndash;2 performance scale at 0.5 and 1.5</p>
        </div>

        <p id="out-note" class="mt-4 text-xs text-slate-600 bg-slate-50 border border-slate-200 rounded-md p-3 leading-relaxed"></p>

        <div id="sample-box" class="mt-3 hidden text-xs bg-amber-50 border border-amber-300 rounded-md p-3">
          <p class="font-semibold text-amber-900">Observed class for comparison</p>
          <p class="mt-1 text-amber-800 num" id="sample-line"></p>
        </div>
      </div>
    </div>
  </section>

  <!-- ==================================================================
       Section 3: the honest evaluation panel.
       ================================================================== -->
  <section class="bg-white rounded-xl shadow-sm border border-slate-200">
    <details open>
      <summary class="flex items-center gap-2 px-5 py-4 font-semibold text-lg hover:bg-slate-50 rounded-t-xl">
        <span class="caret text-slate-400">&#9656;</span>3 &middot; How good is this model, really?
      </summary>
      <div class="px-5 pb-5 space-y-6 text-sm" id="metrics-panel"></div>
    </details>
  </section>

  <!-- ==================================================================
       Section 4: data provenance and limits.
       ================================================================== -->
  <section class="bg-white rounded-xl shadow-sm border border-slate-200 p-5 text-sm">
    <h2 class="font-semibold text-lg mb-3">4 &middot; Data provenance and limitations</h2>
    <div id="provenance" class="space-y-3 text-slate-700"></div>
  </section>
</main>

<footer class="max-w-6xl mx-auto px-5 py-8 text-xs text-slate-500 border-t border-slate-200 mt-4">
  <p>
    Code released under the MIT licence. Data: xAPI-Edu-Data (Kalboard&nbsp;360), distributed
    via Kaggle (Amrieh, Hamtini &amp; Aljarah, 2016).
    Every prediction is computed in your browser from the model weights embedded in this
    file. Nothing is sent anywhere.
  </p>
</footer>

<script>
/* ==========================================================================
   PURE-MODEL CORE — BEGIN
   No DOM, no window, no globals beyond the declarations below.
   ========================================================================== */

const MODEL = __MODEL__;

/* Slider/value ids, in the order buildFeatures() consumes them. */
const IDS = ['raisedhands', 'VisITedResources', 'AnnouncementsView', 'Discussion'];

/* Feature vector — MUST match the order in scripts/train_model.py. */
function buildFeatures(g) {
  return [
    g.raisedhands,          // 0
    g.VisITedResources,     // 1
    g.AnnouncementsView,    // 2
    g.Discussion,           // 3
    g.absence,              // 4  absence band 0/1
    g.semester               // 5  semester 0/1
  ];
}

/* Forward pass through the regression ensemble.
   Trees are flat, stride 5: [feature, threshold, left, right, value];
   a leaf is marked by feature < 0. Child pointers are node indices. */
function regPredict(x) {
  const lr = MODEL.regressor.learning_rate;
  let out = MODEL.regressor.init;
  const trees = MODEL.regressor.trees;
  for (let t = 0; t < trees.length; t++) {
    const a = trees[t];
    let o = 0;
    while (a[o] >= 0) {
      o = 5 * (x[a[o]] <= a[o + 1] ? a[o + 2] : a[o + 3]);
    }
    out += lr * a[o + 4];
  }
  return out;
}

/* Raw additive scores. The page only needs an argmax, so no softmax. */
function clfScores(x) {
  const lr = MODEL.classifier.learning_rate;
  const score = MODEL.classifier.init.slice();
  const trees = MODEL.classifier.trees;
  for (let t = 0; t < trees.length; t++) {
    const a = trees[t].tree;
    let o = 0;
    while (a[o] >= 0) {
      o = 5 * (x[a[o]] <= a[o + 1] ? a[o + 2] : a[o + 3]);
    }
    score[trees[t].cls] += lr * a[o + 4];
  }
  return score;
}

/* Empirical out-of-fold residual percentiles, bucketed by predicted level. */
function predictionBand(perf) {
  const e = MODEL.bands.edges;
  let k = 0;
  while (k < e.length - 2 && perf >= e[k + 1]) k++;
  const b = MODEL.bands.resid[k];
  if (!b) return null;
  return { lo: perf + b.resid_lo10, hi: perf + b.resid_p90, n: b.n };
}

/* ==========================================================================
   PURE-MODEL CORE — END
   ========================================================================== */

const CLASS_HEX = ['#dc2626', '#ca8a04', '#16a34a'];

let last = { perf: 0, cls: 0, name: '—' };

function render() {
  const g = readInputs();
  const x = buildFeatures(g);
  const perf = Math.min(2, Math.max(0, regPredict(x)));
  const score = clfScores(x);
  const cls = score.indexOf(Math.max.apply(null, score));
  const name = MODEL.meta.class_names[cls];
  const band = predictionBand(perf);

  last = { perf: perf, cls: cls, name: name };

  document.getElementById('v-raisedhands').textContent      = g.raisedhands;
  document.getElementById('v-VisITedResources').textContent = g.VisITedResources;
  document.getElementById('v-AnnouncementsView').textContent= g.AnnouncementsView;
  document.getElementById('v-Discussion').textContent       = g.Discussion;

  document.getElementById('out-perf').textContent = perf.toFixed(2);
  document.getElementById('out-class').textContent = name;
  document.getElementById('out-class').style.color = CLASS_HEX[cls];
  document.getElementById('out-band').textContent =
    'Regression band: ' + MODEL.meta.class_names[[0,1,2][Math.min(2, Math.max(0, Math.round(perf)))]];

  const lo = band ? Math.max(0, band.lo) : null;
  document.getElementById('out-lo').textContent = lo === null ? '—' : lo.toFixed(1);
  document.getElementById('out-hi').textContent = band ? band.hi.toFixed(1) : '—';

  document.getElementById('marker-bar').style.left =
    Math.min(99, Math.max(0, perf / 2 * 100)) + '%';

  document.getElementById('out-note').innerHTML = band
    ? 'Among ' + band.n.toLocaleString() + ' historical students with a similar predicted level, the true '
      + 'level landed in this range 80% of the time ('
      + Math.max(0, band.lo).toFixed(1) + '–' + band.hi.toFixed(1)
      + '). The model is reliable for judging <em>whether</em> a student is relatively at risk; the exact '
      + 'level for any single student still carries substantial uncertainty.'
    : 'Not enough historical records in this range to state an interval; showing the point estimate only.';
}

function table(head, rows) {
  let h = '<table class="w-full border-collapse"><thead><tr>';
  head.forEach((c, i) => {
    h += '<th class="' + (i ? 'text-right' : 'text-left') + ' py-1.5 px-2 border-b border-slate-400 font-semibold">' + c + '</th>';
  });
  h += '</tr></thead><tbody>';
  rows.forEach(r => {
    h += '<tr>';
    r.forEach((c, i) => {
      h += '<td class="' + (i ? 'text-right num' : 'text-left') + ' py-1.5 px-2 border-b border-slate-100">' + c + '</td>';
    });
    h += '</tr>';
  });
  return h + '</tbody></table>';
}

function renderMetrics() {
  const M = MODEL.metrics, mt = MODEL.meta;
  let h = '';

  h += '<div><h3 class="font-semibold mb-1">Regression task: predicting performance level (0–2)</h3>'
     + '<p class="text-xs text-slate-500 mb-2">' + mt.cv_note + '. Training rows: '
     + mt.rows_used.toLocaleString() + '.</p>'
     + table(['Method', 'R²', 'RMSE', 'MAE'], [
        ['Always predict the training mean (baseline)', M.regression.baseline_mean.r2.toFixed(3), M.regression.baseline_mean.rmse, M.regression.baseline_mean.mae],
        ['Multiple linear regression', M.regression.linear.r2.toFixed(3), M.regression.linear.rmse, M.regression.linear.mae],
        ['<strong>Gradient-boosted trees (this page)</strong>', '<strong>' + M.regression.model.r2.toFixed(3) + '</strong>', M.regression.model.rmse, M.regression.model.mae]
     ]) + '</div>';

  const dLin = (M.regression.model.r2 - M.regression.linear.r2) * 100;
  h += '<div class="bg-slate-50 border border-slate-200 rounded-lg p-4">'
     + '<p><strong>How to read that table:</strong> the baseline R² is 0 because "always predict the '
     + 'average" cannot explain any variance by construction. Linear regression explains '
     + (M.regression.linear.r2 * 100).toFixed(0) + '% of the variance with six coefficients; the '
     + 'gradient-boosted trees reach ' + (M.regression.model.r2 * 100).toFixed(0) + '%.</p>'
     + '<p class="mt-2"><strong>An honest surprise:</strong> here the extra flexibility of boosting does '
     + '<em>not</em> pay off — it is ' + Math.abs(dLin).toFixed(0) + ' points <em>below</em> plain linear '
     + 'regression. On a dataset this small (' + mt.rows_used + ' students), the boosted model has more '
     + 'than enough capacity to fit noise, and the folds expose that. The lesson is not "boosting is bad" '
     + 'but that <strong>a more complicated model is not automatically a better one</strong>: always put '
     + 'the simple baseline in the table before you trust the fancy result. Roughly '
     + ((1 - M.regression.model.r2) * 100).toFixed(0) + '% of the variance is left unexplained in any '
     + 'case — engagement indicators do not determine outcomes. Prior attainment, motivation and home '
     + 'circumstances do, and none of those are in this file.</p></div>';

  h += '<div><h3 class="font-semibold mb-1">Classification task: three-band performance</h3>'
     + '<p class="text-xs text-slate-500 mb-2">Bands: Low &lt;0.5 &middot; Medium 0.5–1.5 &middot; High &ge;1.5</p>'
     + table(['Method', 'Accuracy', 'Balanced accuracy', 'Class support'], [
        ['Always predict the majority class (baseline)', (M.classification.baseline_majority * 100).toFixed(1) + '%', '33.3%', M.classification.class_support.join(' / ')],
        ['<strong>Gradient-boosted classifier (this page)</strong>',
         '<strong>' + (M.classification.model * 100).toFixed(1) + '%</strong>',
         (M.classification.balanced_accuracy * 100).toFixed(1) + '%', '']
     ]) + '</div>';

  const cm = M.classification.confusion_matrix, cn = mt.class_names;
  h += '<div><h3 class="font-semibold mb-1">Confusion matrix (rows = truth, columns = prediction)</h3>'
     + '<table class="border-collapse"><thead><tr><th class="py-1 px-2"></th>';
  cn.forEach(c => { h += '<th class="py-1 px-3 text-right font-semibold">' + c + '</th>'; });
  h += '</tr></thead><tbody>';
  cm.forEach((row, i) => {
    h += '<tr><td class="py-1 px-2 font-medium">' + cn[i] + '</td>';
    const tot = row.reduce((a, b) => a + b, 0);
    row.forEach((v, j) => {
      h += '<td class="py-1 px-3 text-right num ' + (j === i ? 'bg-green-100 font-semibold' : '')
         + '">' + v.toLocaleString() + '<span class="text-slate-400 text-[10px] ml-1">'
         + (v / tot * 100).toFixed(0) + '%</span></td>';
    });
    h += '</tr>';
  });
  h += '</tbody></table><p class="text-xs text-slate-500 mt-1">Green cells are correct predictions. '
     + 'The model confuses heavily between neighbouring bands — the typical shape of an ordinal '
     + 'education classification task: the boundary between adjacent bands has no sharp definition.</p></div>';

  const dD = (M.classification.model - M.classification.derived_from_regression) * 100;
  h += '<div class="bg-amber-50 border border-amber-300 rounded-lg p-4">'
     + '<p><strong>A comparison that is easy to overlook:</strong> if you skip the dedicated classifier '
     + 'and simply push the regression output through the banding thresholds, accuracy is only <strong>'
     + (M.classification.derived_from_regression * 100).toFixed(1) + '%</strong> — '
     + dD.toFixed(1) + ' percentage points below the standalone classifier&rsquo;s '
     + (M.classification.model * 100).toFixed(1) + '%. The gap comes from flips near the boundaries. '
     + '<strong>"Predict a number, then threshold it" is not the same task as "classify"</strong> — this '
     + 'is a choice about task design, not about which model is better.</p></div>';

  const top = M.feature_importance[0][1];
  h += '<div><h3 class="font-semibold mb-1">Feature importance</h3><table class="w-full">';
  M.feature_importance.forEach(pair => {
    h += '<tr><td class="py-1 px-2 w-44 text-xs">' + pair[0] + '</td>'
       + '<td class="px-2 py-1"><div class="bg-blue-500 rounded" style="height:9px;width:'
       + (pair[1] / top * 100).toFixed(1) + '%"></div></td>'
       + '<td class="px-2 py-1 num text-xs text-right w-16">' + pair[1].toFixed(3) + '</td></tr>';
  });
  h += '</table><p class="text-xs text-slate-500 mt-2">The single most important feature is <strong>the '
     + 'number of course resources visited</strong>, followed by the absence band. This is a familiar result '
     + 'in learning analytics: <em>behavioural engagement</em> with course materials is among the strongest '
     + 'early signals of performance. Notice, however, that this is a correlation in one cohort, not proof '
     + 'that opening more resources causes higher grades.</p></div>';

  h += '<div class="bg-rose-50 border border-rose-300 rounded-lg p-4">'
     + '<p><strong>A feature deliberately thrown away: the final grade.</strong> The dataset also encodes the '
     + 'student&rsquo;s class result, which is exactly the thing we are trying to predict. Including it would '
     + 'produce a near-perfect score and teach nothing. The model uses only indicators that are available '
     + '<em>earlier</em> — engagement counts, absence band and semester — so the prediction is one a tutor '
     + 'could actually act on during the course.</p></div>';

  h += '<div class="bg-slate-50 border border-slate-200 rounded-lg p-4">'
     + '<p><strong>External validity:</strong> the model has only learned the engagement–performance '
     + 'relationship of one cohort using the Kalboard&nbsp;360 platform. Applying it to a different '
     + 'institution, age group or platform will degrade markedly. Treat the numbers here as a demonstration '
     + 'of "what machine learning can achieve on this dataset", not as a live early-warning system.</p></div>';

  document.getElementById('metrics-panel').innerHTML = h;
}

function renderProvenance() {
  const mt = MODEL.meta;
  const rows = [
    '<p><strong>Dataset:</strong> ' + mt.dataset + '. Distributed via Kaggle. '
    + mt.raw_rows.toLocaleString() + ' student records. This model trains on <strong>'
    + mt.rows_used.toLocaleString() + '</strong>.</p>',

    '<p><strong>Six features.</strong> Raised hands, resources visited, announcements viewed, discussion '
    + 'messages, an absence band (under 7 days vs 7 or more) and the semester. <strong>Excluded on '
    + 'purpose:</strong> the final grade and anything derived from it, plus nationality, place of birth and '
    + 'parental survey answers. Excluding the final grade is what prevents the otherwise trivial '
    + '"predict the result from the result" leak.</p>',

    '<p><strong>Models (scikit-learn):</strong> regression via GradientBoostingRegressor (n_estimators='
    + mt.reg_params.n_estimators + ', max_depth=' + mt.reg_params.max_depth + ', learning_rate='
    + mt.reg_params.learning_rate + '); classification via GradientBoostingClassifier (n_estimators='
    + mt.clf_params.n_estimators + ', max_depth=' + mt.clf_params.max_depth + ', learning_rate='
    + mt.clf_params.learning_rate + '). Random seed ' + mt.seed + '.</p>',

    '<p><strong>A note on fairness.</strong> A model that predicts risk can also create it, if a tutor stops '
    + 'supporting a student because the model says they are fine, or labels a student because the model says '
    + 'they are not. Any real deployment of a system like this needs to be evaluated for bias across groups '
    + 'and used to <em>direct support</em>, never to justify withdrawal of it.</p>',

    '<p class="text-xs text-slate-500">Citation: Amrieh, E. A., Hamtini, T., &amp; Aljarah, I. (2016). Mining '
    + 'Educational Data to Predict Student&rsquo;s Academic Performance using Ensemble Methods. '
    + '<em>International Journal of Database Theory and Application, 9</em>(8), 119&ndash;136.</p>'
  ];
  document.getElementById('provenance').innerHTML = rows.join('');
}

/* ==========================================================================
   Input reading, wiring, initialisation.
   ========================================================================== */
let absenceBand = '0';
let semesterBand = '0';

function readInputs() {
  const g = {};
  for (const id of IDS) g[id] = parseFloat(document.getElementById('in-' + id).value);
  g.absence = parseFloat(absenceBand);
  g.semester = parseFloat(semesterBand);
  return g;
}

function paintButtons(sel, onValue) {
  const btns = document.querySelectorAll(sel + ' button');
  for (let i = 0; i < btns.length; i++) {
    const b = btns[i];
    const on = b.dataset.v === onValue;
    b.className = 'py-2 rounded-md text-sm border ' + (on
      ? 'bg-blue-600 text-white border-blue-600 font-medium'
      : 'bg-white text-slate-600 border-slate-300 hover:bg-slate-50');
  }
}

function init() {
  const mt = MODEL.meta;

  for (const id of IDS) {
    const el = document.getElementById('in-' + id);
    const [lo, hi] = mt.input_ranges[id];
    el.min = Math.floor(lo); el.max = Math.ceil(hi); el.step = 1;
  }

  const d = mt.defaults;
  for (const id of IDS) document.getElementById('in-' + id).value = d[id];

  const R = mt.input_ranges;
  for (const k of IDS) {
    document.getElementById('r-' + k).textContent = R[k][0] + ' – ' + R[k][1];
  }
  document.getElementById('hdr-rows').textContent = mt.rows_used.toLocaleString();
  document.getElementById('hdr-raw').textContent = mt.raw_rows.toLocaleString();
  document.getElementById('hdr-folds').textContent = mt.cv_folds;

  const fmtRange = (sizes) => {
    const lo = Math.min.apply(null, sizes), hi = Math.max.apply(null, sizes);
    return lo === hi ? lo.toLocaleString() : lo.toLocaleString() + '–' + hi.toLocaleString();
  };
  document.getElementById('hdr-testsize').textContent = fmtRange(mt.fold_test_sizes);
  document.getElementById('hdr-trainsize').textContent = fmtRange(mt.fold_train_sizes);

  for (const id of IDS) {
    document.getElementById('in-' + id).addEventListener('input', render);
  }
  document.querySelectorAll('#in-absence button').forEach(b => {
    b.addEventListener('click', function () { absenceBand = this.dataset.v; paintButtons('#in-absence', absenceBand); render(); });
  });
  document.querySelectorAll('#in-semester button').forEach(b => {
    b.addEventListener('click', function () { semesterBand = this.dataset.v; paintButtons('#in-semester', semesterBand); render(); });
  });

  let si = 0;
  document.getElementById('btn-random').addEventListener('click', function () {
    const s = MODEL.samples[si % MODEL.samples.length];
    si++;
    for (const id of IDS) document.getElementById('in-' + id).value = s[id];
    absenceBand = String(s.absence_high);
    semesterBand = String(s.semester_s);
    paintButtons('#in-absence', absenceBand);
    paintButtons('#in-semester', semesterBand);
    render();
    document.getElementById('sample-box').classList.remove('hidden');
    document.getElementById('sample-line').innerHTML =
      '<strong>Observed class: ' + s.observed_class + '</strong> (level ' + s.observed_perf.toFixed(0)
      + '); model predicted ' + last.name + ' (level ' + last.perf.toFixed(2) + ').';
  });

  paintButtons('#in-absence', absenceBand);
  paintButtons('#in-semester', semesterBand);
  renderMetrics();
  renderProvenance();
  render();
}

init();
</script>
</body>
</html>
'''

HTML = HTML.replace('__CSS__', CSS).replace('__MODEL__', MODEL_JS)
with open(f'{HERE}/index.html', 'w', encoding='utf-8') as f:
    f.write(HTML)
print('wrote index.html', len(HTML), 'bytes')
